version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: restore server cache
          keys:
            - my-project-server-{{ .Branch }}-{{ checksum "client/package.json" }}
            - my-project-server-{{ .Branch }}
            - my-project-server-
      - restore_cache:
          name: restore client cache
          keys:
            - my-project-client-{{ .Branch }}-{{ checksum "client/package.json" }}
            - my-project-client-{{ .Branch }}
            - my-project-client-
      - run:
          name: install client dependencies
          command: |
            cd client
            npm install
      - run:
          name: install server dependencies
          command: npm install
      - save_cache:
          key: my-project-client-{{ .Branch }}-{{ checksum "client/package.json" }}
          paths:
            - "client/node_modules"
      - save_cache:
          key: my-project-server-{{ .Branch }}-{{ checksum "client/package.json" }}
          paths:
            - "node_modules"
      - run:
          name: run server test
          command: npm run server-test-ci
      - run:
          name: run client test
          command: |
            cd client
            npm run test-ci
      - run:
          name: run linter
          command: npm run lint
